### ISSUE TITLE
Высвобождать память нужно правильно

### ISSUE THREAD

**Issue by StriderAJR** [Oxid15/CppLabs#1]
@Oxid15 Как насчет
```
delete m;
```
Все-таки удалять весь массив? Типа `delete` и `delete[]` - разные вещи.

**Comment by Oxid15** [comment]
А в чём разница вот конкретно для этого задания? Я думал, раз вычисления с массивом закончены, то можно освободить целиком.И в таком случае, когда используется освобождение только одной ячейки?Если я правильно понял суть.

**Comment by Oxid15** [comment]
@StriderAJR 
На практике всё выяснилось, вопрос снят, уже поправил.
