### ISSUE TITLE
Имя репозитория

### ISSUE THREAD

**Issue by StriderAJR** [Oxid15/CppLabs#2]
По секрету могу сказать, что репо можно переименовывать.
https://help.github.com/articles/renaming-a-repository/

**Comment by Oxid15** [comment]
@StriderAJR 
а нужно?

**Comment by StriderAJR** [comment]
@Oxid15 Ну хотелось бы.

**Comment by Oxid15** [comment]
@StriderAJR 
А на какое? CppLabs стоит ведь. Адекватное вроде.

**Comment by StriderAJR** [comment]
@Oxid15 
-CppLabs стоит сейчас. А именно, что нужно CppLabs.

**Comment by Oxid15** [comment]
@StriderAJR Понял, я так и думал. Уже сменил.
