### ISSUE TITLE
Вызов дьявола

### ISSUE THREAD

**Issue by StriderAJR** [Oxid15/CppLabs#3]
Тут только что был вызван дьявол.
```
int* a = new int[];
```
Задание: понять почему.

**Comment by Oxid15** [comment]
@StriderAJR  К какому это заданию? Не могу найти такую строку. Суть в том, что не указана длина массива?

**Comment by StriderAJR** [comment]
@Oxid15 4 задание 2 лабы. Да, в этом проблема. И нужно понять почему

**Comment by Oxid15** [comment]
@StriderAJR  Ну, если я инициализирую динамический массив, оператору new нужно обязательно знать сколько памяти резервировать, длина массива, если она не указана сразу, должна быть указана далее по ходу программы. В последней версии подобной строки уже нет и длина задаётся переменной. Программа работает корректно.
